# site settings
#baseurl: /vrdocs
#google_analytics: UA-1622439-5

# theme
theme: bulma-clean-theme
#remote_theme: chrisrhymes/bulma-clean-theme
permalink: pretty

# plugins
plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-github-metadata

# defaults
defaults:
  - scope:
      path: "**/*.md"
    values:
      hero_height: is-small
      layout: page
      hide_hero: true
  - scope:
      path: "docs/*.md"
    values:
      layout: post
      author: Richard Musil
      menubar: true
      menubar_toc: true

# site SEO
title: VR Docs
author: Richard Musil
description: Some thoughts on VR
social:
  name: Richard Musil
  links:
    - https://github.com/risa2000

